### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar pelicula por ID
GET http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08

### Recuperar todas las peliculas por género
GET http://localhost:1234/movies?genre=drama

### Crear una pelicula con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "Hola como andas",
  "year": 1975,
  "director": "James Cameron",
  "duration": 175,
  "rate": 2,
  "poster": "https://m.media-amazon.com/images/I/91Rc8cAmnAL._AC_UF1000,1000_QL80_.jpg",
  "genre": ["Horror"]
}

### Actualizar una  pelicula
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "SQL": "SELECT * FROM USERS",
  "id": 1,
  "title":  "Bue",
  "year": 1998,
  "genre": [
    "Policias",
    "Action",
    "Horror"
  ]
}
